addSbtPlugin("com.geirsson"       % "sbt-ci-release"           % "1.5.7")
addSbtPlugin("com.codecommit"     % "sbt-github-actions"       % "0.13.0")
addSbtPlugin("com.typesafe"       % "sbt-mima-plugin"          % "1.0.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.7.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.1.0")
